plugins {
    id 'com.blackbuild.klum-ast-schema' version "${klumAstVersion}"
}

group = 'org.klum.catwalk.showcase.smarthome'
version = providers.gradleProperty('journeyVersion').get()

klumSchema {
    groovyVersion = '3'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

base {
    archivesName = 'domain-api'
}
