plugins {
    id 'com.blackbuild.klum-ast-schema' version "${klumAstVersion}"
}

group = 'org.klum.catwalk.showcase.helm'
version = providers.gradleProperty('journeyVersion').get()

klumSchema {
    groovyVersion = '3'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

base {
    archivesName = 'schema'
}

dependencies {
    implementation "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:${jacksonYamlVersion}"
}
